### ISSUE TITLE
Is this project alive or are you looking for new contributors?

### ISSUE THREAD

**Issue by volekthefndwarf** [Akkadius/EQEmuEOC#4]
Wouldn't mind helping out on this looks, gotta background in PHP and many other languages.

**Comment by Akkadius** [comment]
EOC is widely used by the EQEmu community, but as it stands I don't plan on adding onto it, but it will continue to exist until there is something else to replace functionality, I plan to do a full re-write using a different tech stack. If you want to discuss this more with me, hit me up in the EQEmu discord 

https://discord.gg/QHsm7CD
